### ISSUE TITLE
Error on homepage

### ISSUE THREAD

**Issue by hnnweb** [citruspi/Spotify-Notifications#74]
The trademark notice on the homepage is wrong.

"Spotify is a registered trademark of Spotify AB Inc."

Spotify is actually a registered trademark of Spotify AB.

AB in Sweden is the same as Inc.

Attaching screenshot from Spotify.com/us/:
![screen shot 2016-10-26 at 14 43 14](https://cloud.githubusercontent.com/assets/3874960/19726307/8e60fd8c-9b8a-11e6-8d63-5bcb4a35eab4.png)

**Comment by sebj** [comment]
Probably better to file an issue at https://github.com/citruspi/spotify-notifications.citruspi.io where website code actually is, but I'll mention @citruspi because it's a small change.

**Comment by citruspi** [comment]
Thanks for the heads up, @hnnweb, I've fixed the website.

**Comment by hnnweb** [comment]
@citruspi Nope, you havent... Still an issue on the bottom...
